language: node_js
node_js:
- '16.20.2'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # REGISTRY_TOKEN(editor=cozy, app=auchandrive)
  - secure: p9PgzrF+wCtiPNfhgi9zcQz+11HwoOxi2QiokGjJfhuTUei4yfPckyG0MMOh0nfB9NbRzAiHx+ENaVingZ7YZHSAP8miu1W6zCdiYM3lRpGdkD5d3PBuEo57YZaax/eCOFA34bBfpILFHVLsLzMbfYGDXl7KDhJOGXbrDU97pzBicuGXMgixTJ4rVA6LZ6D1tKHo8v+rMSp60a1dWoXiMEh6jSrLxbIW8YOG4KW9YY0zthYkODAxyagu8huL66+OGgkffRqNNBMcYVmq32fRWyWVnDMOxHzYEVcdS5iG5qCJmYfdKJcQ1D/i0KuUew8ysFOrA4l/oK3mjfD17Rf34c/tdieVA1XXSEvB5dauolXiaKuudi++sOa4YaUh98Zg5nOMW9z2a3ZAD2niWktrcfjXnl3Wrt5oWKm3HWLnXpYU2Uh1rl7aP1BKdPqWMJ2DLCgaii458UjGCTBkOgyVZnwHoByv+A+DTOlebzGg36iFoMTlpyjEx2x+/0+nWv7LmKcBK2LC5NaVMgnV44Y5ly34r3T0fZsCRg8UAtOhDKsSxJJCC/Qnmqc31f3pJYGEIKeE7uSJa+2ttnhXz0kcPDPEotC9gen566Sct2OMJ4QawF5qLG8ycqXox9fJ3m4guzLWX60MagaN8+yV59AydX/UyHXdqCKRjmKIf6HPvaI=
  # MATTERMOST_HOOK_URL
  - secure: VJSOz4UJ46KB6s6bdr9LNmCTn44loyrQzJ64I+3FmF9isZxwfhqsfYfTjkuZritEVAuEqrV26qC28ZrJyaku7NENDgpdjUg90s5IIfBZfk9E9vUT8ZhNzHFbQcHi645QKN77KWgIT6+3Dnk9Q07t/Ksx9NJindXW9H7IStFPhGe7SM6XrArM89XcCoTMpUZqDb6Wrdal/FCv57ZNYxhAFjW3IKml1AZgXtlfFmzhMFn8IvwwrZutth0pj4MB0EaX4wI3jorzoWAPm+3zV6UANnETUzqD9O5u0kvEJkXXhV2+IOXKaHG3M98ViTW0wVLqk0LBMDqWM+gKgtKAVJiTE7o7vzMt6+vg7YlnS65Opk1WuPnZa7Ih+k/TYFJoD2K7tILr9Tz4XY8dsWeg6f0nIWpDK8evldfh764j18M/BV/4jItwhfwC3gfAgbRRqBP9fVpGuQ7VZrI4XAC9l9Ip1a3/6SaVEFNm0r+esaVGw2+mhJLMa1fMR/TG0T+CsrlX2dZWF0oF9w1qtuqzYjPTw8+8qKcst0hScpkxEjipA/2e1jldqvEKpeqxhLHwv+93fUiVLXf8q1lpQ/0ajlOAZ3Eq1mzJbf2Tsn+gQ7UTyUnlvCzeB2x7bYp7SyxbOYL31J7mrYwOSnrahv5/lu+wm0x3l2ljUScFN+AeMzD4/RU=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
